import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations {
  static const String _languageKey = 'app_language';
  static const String _languageEn = 'en';
  static const String _languageSk = 'sk';

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appTitle': 'Money Mansion',
      'settings': 'Settings',
      'gamePreferences': 'Game preferences and options',
      'gameInfo': 'Game information',
      'language': 'Language',
      'backgroundMusic': 'Background music',
      'musicVolume': 'Music volume',
      'gameTab': 'Game',
      'inventoryTab': 'Inventory',
      'shopTab': 'Shop',
      'goalsTab': 'Goals',
      'calendarTab': 'Calendar',
      'financialTab': 'Financial',
      'settingsTab': 'Settings',
      'coins': 'Coins',
      'money': 'Money',
      'date': 'Date',
      'room': 'Room',
      'editRoom': 'Edit Room',
      'languageEnglish': 'English',
      'languageSlovak': 'Slovak',
      'selectLanguage': 'Select language',
      'unsavedChanges': 'Unsaved changes',
      'saveChanges': 'Save changes',
      'discardChanges': 'Discard changes',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'back': 'Back',
      'ok': 'OK',
      'inventory': 'Inventory',
      'shop': 'Shop',
      'goals': 'Goals',
      'calendar': 'Calendar',
      'financial': 'Financial',
      'balance': 'Balance',
      'income': 'Income',
      'expense': 'Expense',
      'transactions': 'Transactions',
      'addTransaction': 'Add transaction',
      'goalName': 'Goal name',
      'goalDescription': 'Description',
      'targetAmount': 'Target amount',
      'currentAmount': 'Current amount',
      'rewardCoins': 'Reward coins',
      'addGoal': 'Add goal',
      'goalCompleted': 'Goal completed!',
      'completeGoal': 'Complete goal',
      'itemName': 'Item name',
      'itemPrice': 'Price',
      'buy': 'Buy',
      'sell': 'Sell',
      'owned': 'Owned',
      'month': 'Month',
      'year': 'Year',
      'today': 'Today',
      'areYouSure': 'Are you sure?',
      'confirmation': 'Confirmation',
      'noItemsYet': 'No items yet',
      'yourItemsWillAppearHere': 'Your items will appear here',
      'notEnoughCoins': 'Not enough coins!',
      'needCoinsHave': 'Need {need}, have {have}',
      'purchasedFor': '{item} purchased for {cost} coins!',
      'itemPurchasedSuccessfully': 'Item purchased successfully!',
      'furniture': 'Furniture',
      'realEstate': 'Real estate',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'monday': 'Mon',
      'tuesday': 'Tue',
      'wednesday': 'Wed',
      'thursday': 'Thu',
      'friday': 'Fri',
      'saturday': 'Sat',
      'sunday': 'Sun',
      'todayLabel': 'Today',
      'errorLoadingGoals': 'Error loading goals',
      'createNewGoal': 'Create new goal',
      'goalTitle': 'Goal title',
      'coinsReward': 'Coins reward',
      'targetMoneyAmount': 'Target money amount (EUR)',
      'selectDeadline': 'Select deadline',
      'addNew': 'Add new',
      'noTransactions': 'No transactions yet',
      'addTransactionLabel': 'Add transaction',
      'amountEuro': 'Amount (EUR)',
      'selectType': 'Select type',
      'selectGoal': 'Select goal (optional)',
      'createdAt': 'Created at',
      'pickDate': 'Pick date',
      'enterGoalTitle': 'Please enter a goal title',
      'goalCreatedSuccessfully': 'Goal created successfully',
      'failedToCreateGoal': 'Failed to create goal',
      'createGoal': 'Create goal',
      'refreshGoals': 'Refresh goals',
      'failedToCompleteGoal': 'Failed to complete goal',
      'goalDeleted': 'Goal deleted',
      'failedToDeleteGoal': 'Failed to delete goal',
      'noGoalAllocation': 'No goal allocation',
      'refresh': 'Refresh',
      'noGoal': 'No goal',
      'plus': '+',
      'minus': '-',
      'statistics': 'Statistics',
      'gain': 'Gain',
      'purchase': 'Purchase',
      'reassignFunds': 'Reassign funds',
      'fromGoal': 'From goal',
      'toGoal': 'To goal',
      'amount': 'Amount',
      'note': 'Note',
      'amountExceedsAvailableGoalFunds': 'Amount exceeds available goal funds.',
      'amountExceedsGoalTarget': 'Amount would exceed the target goal.',
      'fundsReassignedSuccessfully': 'Funds reassigned successfully',
      'addGainOrPurchase': 'Add gain / purchase',
      'editTransaction': 'Edit transaction',
      'noTransactionsYetTapAdd': 'No transactions yet. Tap + to add one!',
      'moneyAssignedAndGoalCompleted': 'Money assigned and goal completed!',
      'moneyAssignedToGoal': 'Money assigned to goal',
      'assignMoneyToGoal': 'Assign money to {goal}',
      'availableBalance': 'Available balance: {amount}',
      'amountExceedsCurrentAppBalance': 'Amount exceeds current app balance.',
      'assignMoney': 'Assign money',
      'goalAmount': 'Goal amount',
      'goalCompletedChrumkaOnly': 'Goal completed! +1 Chrumka',
      'goalCompletedCoinsAndChrumka': 'Goal completed! +{coins} coins & +1 Chrumka',
      'goalDeletedAndMoneyReturned': 'Goal deleted and money returned to balance',
      'difficultyEasy': 'Easy',
      'difficultyMedium': 'Medium',
      'difficultyHard': 'Hard',
      'difficulty': 'Difficulty',
      'rewardLabel': 'Reward',
      'goalsActive': 'Active Goals',
      'goalsCompleted': 'Completed Goals',
      'goalsEmptyTitle': 'No goals yet',
      'goalsEmptySubtitle': 'Create your first goal to get started',
      'goalCreateSuccess': 'Goal created successfully',
      'goalCreateFail': 'Failed to create goal',
      'goalCompleteProgressError': 'Goal can only be completed at 100% progress.',
      'goalLoadFail': 'Failed to load goals.',
      'chrumkoTipLabel': "Chrumko's tip",
      'chrumkoTipDismiss': 'Tap to dismiss',
      'chrumkoTip0': 'I always set aside part of my money. Try it too!',
      'chrumkoTip1': 'Think first, then buy.',
      'chrumkoTip2': 'I track my expenses so I know where my money goes.',
      'chrumkoTip3': 'Even small savings grow over time.',
      'chrumkoTip4': 'When I plan my purchases, I save more money.',
      'chrumkoTip5': 'I always keep a reserve for unexpected things.',
      'chrumkoTip6': 'A budget helps me stay in control of my money.',
      'chrumkoTip7': 'I do not have to buy everything right away. Waiting can help.',
      'chrumkoTip8': 'Every saved euro is a step toward my goals.',
      'chrumkoTip9': 'Thoughtful decisions make money a great helper.',
      'chrumkoTip10': 'I save up for things that really matter to me.',
      'chrumkoTip11': 'When I save regularly, my savings grow faster.',
      'chrumkoTip12': 'Before buying, I ask: do I really need this?',
      'chrumkoTip13': 'Financial discipline helps me achieve my dreams.',
      'chrumkoTip14': 'Money is a tool, not a goal.',
    },
    'sk': {
      'appTitle': 'Money Mansion',
      'settings': 'Nastavenia',
      'gamePreferences': 'Herne preferencie a moznosti',
      'gameInfo': 'Informacie o hre',
      'language': 'Jazyk',
      'backgroundMusic': 'Hudba na pozadi',
      'musicVolume': 'Hlasitost hudby',
      'gameTab': 'Hra',
      'inventoryTab': 'Inventar',
      'shopTab': 'Obchod',
      'goalsTab': 'Ciele',
      'calendarTab': 'Kalendar',
      'financialTab': 'Financie',
      'settingsTab': 'Nastavenia',
      'coins': 'Mince',
      'money': 'Peniaze',
      'date': 'Datum',
      'room': 'Izba',
      'editRoom': 'Upravit izbu',
      'languageEnglish': 'English',
      'languageSlovak': 'Slovencina',
      'selectLanguage': 'Vyberte jazyk',
      'unsavedChanges': 'Neulozene zmeny',
      'saveChanges': 'Ulozit zmeny',
      'discardChanges': 'Zahodit zmeny',
      'save': 'Ulozit',
      'cancel': 'Zrusit',
      'delete': 'Vymazat',
      'edit': 'Upravit',
      'add': 'Pridat',
      'back': 'Spat',
      'ok': 'OK',
      'inventory': 'Inventar',
      'shop': 'Obchod',
      'goals': 'Ciele',
      'calendar': 'Kalendar',
      'financial': 'Financie',
      'balance': 'Zostatok',
      'income': 'Prijem',
      'expense': 'Vydaj',
      'transactions': 'Transakcie',
      'addTransaction': 'Pridat transakciu',
      'goalName': 'Nazov ciela',
      'goalDescription': 'Popis',
      'targetAmount': 'Cielova suma',
      'currentAmount': 'Aktualna suma',
      'rewardCoins': 'Odmena v minciach',
      'addGoal': 'Pridat ciel',
      'goalCompleted': 'Ciel splneny!',
      'completeGoal': 'Splnit ciel',
      'itemName': 'Nazov polozky',
      'itemPrice': 'Cena',
      'buy': 'Kupit',
      'sell': 'Predat',
      'owned': 'Vlastni',
      'month': 'Mesiac',
      'year': 'Rok',
      'today': 'Dnes',
      'areYouSure': 'Ste si isti?',
      'confirmation': 'Potvrdenie',
      'noItemsYet': 'Zatial nie su polozky',
      'yourItemsWillAppearHere': 'Vase polozky sa objavia tu',
      'notEnoughCoins': 'Nedostatok minci!',
      'needCoinsHave': 'Potrebujete {need}, mate {have}',
      'purchasedFor': '{item} kupene za {cost} minci!',
      'itemPurchasedSuccessfully': 'Nakup bol uspesny!',
      'furniture': 'Nabytok',
      'realEstate': 'Nehnutelnosti',
      'january': 'Januar',
      'february': 'Februar',
      'march': 'Marec',
      'april': 'April',
      'may': 'Maj',
      'june': 'Jun',
      'july': 'Jul',
      'august': 'August',
      'september': 'September',
      'october': 'Oktober',
      'november': 'November',
      'december': 'December',
      'monday': 'Po',
      'tuesday': 'Ut',
      'wednesday': 'St',
      'thursday': 'Stv',
      'friday': 'Pi',
      'saturday': 'So',
      'sunday': 'Ne',
      'todayLabel': 'Dnes',
      'errorLoadingGoals': 'Chyba pri nacitani cielov',
      'createNewGoal': 'Vytvorit novy ciel',
      'goalTitle': 'Nazov ciela',
      'coinsReward': 'Odmena v minciach',
      'targetMoneyAmount': 'Cielova suma penazi (EUR)',
      'selectDeadline': 'Vyberte deadline',
      'addNew': 'Pridat nove',
      'noTransactions': 'Zatial bez transakcii',
      'addTransactionLabel': 'Pridat transakciu',
      'amountEuro': 'Suma (EUR)',
      'selectType': 'Vyberte typ',
      'selectGoal': 'Vyberte ciel (volitelne)',
      'createdAt': 'Vytvorene',
      'pickDate': 'Vyberte datum',
      'enterGoalTitle': 'Prosim zadajte nazov ciela',
      'goalCreatedSuccessfully': 'Ciel bol uspesne vytvoreny',
      'failedToCreateGoal': 'Chyba pri vytvarani ciela',
      'createGoal': 'Vytvorit ciel',
      'refreshGoals': 'Obnovit ciele',
      'failedToCompleteGoal': 'Chyba pri splneni ciela',
      'goalDeleted': 'Ciel bol vymazany',
      'failedToDeleteGoal': 'Chyba pri vymazavani ciela',
      'noGoalAllocation': 'Bez pridelenia cielu',
      'refresh': 'Obnovit',
      'noGoal': 'Bez ciela',
      'plus': '+',
      'minus': '-',
      'statistics': 'Statistika',
      'gain': 'Prijem',
      'purchase': 'Nakup',
      'reassignFunds': 'Presunut peniaze',
      'fromGoal': 'Z ciela',
      'toGoal': 'Do ciela',
      'amount': 'Suma',
      'note': 'Poznamka',
      'amountExceedsAvailableGoalFunds': 'Suma prekracuje dostupne peniaze ciela.',
      'amountExceedsGoalTarget': 'Suma by prekrocila cielovu sumu.',
      'fundsReassignedSuccessfully': 'Peniaze boli uspesne presunute',
      'addGainOrPurchase': 'Pridat prijem / nakup',
      'editTransaction': 'Upravit transakciu',
      'noTransactionsYetTapAdd': 'Zatial nie su ziadne transakcie. Klepnite na + a pridajte jednu.',
      'moneyAssignedAndGoalCompleted': 'Peniaze priradene a ciel splneny!',
      'moneyAssignedToGoal': 'Peniaze boli priradene k cielu',
      'assignMoneyToGoal': 'Priradit peniaze k cielu {goal}',
      'availableBalance': 'Dostupny zostatok: {amount}',
      'amountExceedsCurrentAppBalance': 'Suma prekracuje aktualny zostatok aplikacie.',
      'assignMoney': 'Priradit peniaze',
      'goalAmount': 'Suma ciela',
      'goalCompletedChrumkaOnly': 'Ciel splneny! +1 Chrumka',
      'goalCompletedCoinsAndChrumka': 'Ciel splneny! +{coins} minci a +1 Chrumka',
      'goalDeletedAndMoneyReturned': 'Ciel bol vymazany a peniaze sa vratili do zostatku',
      'difficultyEasy': 'Lahka',
      'difficultyMedium': 'Stredna',
      'difficultyHard': 'Tazka',
      'difficulty': 'Narocnost',
      'rewardLabel': 'Odmena',
      'goalsActive': 'Aktivne ciele',
      'goalsCompleted': 'Dokoncene ciele',
      'goalsEmptyTitle': 'Zatial ziadne ciele',
      'goalsEmptySubtitle': 'Vytvorte si prvy ciel',
      'goalCreateSuccess': 'Ciel bol uspesne vytvoreny',
      'goalCreateFail': 'Nepodarilo sa vytvorit ciel',
      'goalCompleteProgressError': 'Ciel je mozne dokoncit len pri 100% progrese.',
      'goalLoadFail': 'Nepodarilo sa nacitat ciele.',
      'chrumkoTipLabel': 'Tip od Chrumka',
      'chrumkoTipDismiss': 'Klepnite pre zavretie',
      'chrumkoTip0': 'Vzdy si odlozim cast penazi. Skus to aj ty!',
      'chrumkoTip1': 'Najprv premyslaj, az potom nakupuj.',
      'chrumkoTip2': 'Sledujem svoje vydavky, aby som vedel, kam moje peniaze idu.',
      'chrumkoTip3': 'Aj male uspory casom narastu.',
      'chrumkoTip4': 'Ked planujem nakupy, usetrim viac penazi.',
      'chrumkoTip5': 'Vzdy si nechavam rezervu na necakane veci.',
      'chrumkoTip6': 'Rozpocet mi pomaha mat peniaze pod kontrolou.',
      'chrumkoTip7': 'Nemusim kupit vsetko hned. Niekedy sa oplati pockat.',
      'chrumkoTip8': 'Kazde usetrene euro je krok k mojim cielom.',
      'chrumkoTip9': 'Premyslene rozhodnutia robia z penazi dobreho pomocnika.',
      'chrumkoTip10': 'Setrim na veci, ktore su pre mna naozaj dolezite.',
      'chrumkoTip11': 'Ked setrim pravidelne, moje uspory rastu rychlejsie.',
      'chrumkoTip12': 'Pred nakupom sa opytam: naozaj to potrebujem?',
      'chrumkoTip13': 'Financna disciplina mi pomaha plnit si sny.',
      'chrumkoTip14': 'Pamataj: peniaze su nastroj, nie ciel.',
    },
  };

  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }

  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? _languageEn;
  }

  static String translate(String key, {String language = _languageEn}) {
    return _translations[language]?[key] ??
        _translations[_languageEn]?[key] ??
        key;
  }

  static List<String> getChrumkoTips(String language) {
    return List.generate(
      15,
      (i) => translate('chrumkoTip$i', language: language),
    );
  }

  static List<String> getSupportedLanguages() {
    return [_languageEn, _languageSk];
  }

  static String getLanguageName(String languageCode) {
    return languageCode == _languageSk ? 'Slovencina' : 'English';
  }
}
