/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

import 'package:flutter/widgets.dart'; 

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const Widget home = ImageWidget(iconData: IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget target = ImageWidget(iconData: IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget basket = ImageWidget(iconData: IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget chart_bar = ImageWidget(iconData: IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget user = ImageWidget(iconData: IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget settings = ImageWidget(iconData: IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget money = ImageWidget(iconData: IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget coins = ImageWidget(iconData: IconData(0xf51e, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget robot = ImageWidget(iconData: IconData(0xf544, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget cat = ImageWidget(assetImage: "assets/images/alien150.png");
  static const Widget house = ImageWidget(assetImage: "assets/images/house32.png");
  static const Widget man = ImageWidget(assetImage: "assets/images/man32.png");
  static const Widget task = ImageWidget(assetImage: "assets/images/task32.png");
  static const Widget stats = ImageWidget(assetImage: "assets/images/stats32.png");
  static const Widget shop = ImageWidget(assetImage: "assets/images/shop32.png");
}

class ImageWidget extends StatelessWidget {
  const ImageWidget({Key? key, this.assetImage = null, this.iconData = null, this.width=150, this.height=150}) : super(key: key);
  final String? assetImage;
  final IconData? iconData;
  final double width;
  final double height;

  @override
  Widget build(BuildContext context) {
    if (this.assetImage != null) {
      return Image.asset(
        this.assetImage!, 
        width: this.width,                
        height: this.height,              
      );
    }
    else if(this.iconData != null) {
      return Icon(this.iconData);
    }
    else {
      return Icon(IconData(0xf0555, fontFamily: 'MaterialIcons'));
    }

  }
}

