/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

import 'package:flutter/widgets.dart'; 

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const Widget home = ImageWidget(iconData: IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget target = ImageWidget(iconData: IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget basket = ImageWidget(iconData: IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget chart_bar = ImageWidget(iconData: IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget user = ImageWidget(iconData: IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget settings = ImageWidget(iconData: IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget money = ImageWidget(iconData: IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget coins = ImageWidget(iconData: IconData(0xf51e, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget robot = ImageWidget(iconData: IconData(0xf544, fontFamily: _kFontFam, fontPackage: _kFontPkg));
  static const Widget cat = ImageWidget(assetImage: "assets/images/alien150.png");
  static const Widget house = ImageWidget(assetImage: "assets/images/house178.png");
  static const Widget man = ImageWidget(assetImage: "assets/images/man178.png");
  static const Widget task = ImageWidget(assetImage: "assets/images/task178.png");
  static const Widget shop = ImageWidget(assetImage: "assets/images/stats178.png");
  static const Widget chrumka = ImageWidget(assetImage: "assets/images/chrumka 32.png");
  static const Widget kojn = ImageWidget(assetImage: "assets/images/coinik150.png");
  static const Widget payment = ImageWidget(assetImage: "assets/images/platby.png");
  static const Widget chrumko_coin = ImageWidget(assetImage: "assets/images/chrumko_coin.png");
  static const Widget cereal = ImageWidget(assetImage: "assets/images/cereal_bar.png");
  static const Widget barter = ImageWidget(assetImage: "assets/images/egg_bread.png");
  static const Widget tie = ImageWidget(assetImage: "assets/images/tie.png");
  static const Widget juice = ImageWidget(assetImage: "assets/images/dzus_keks.png");
  static const Widget look = ImageWidget(assetImage: "assets/images/look.png");
  static const Widget idea = ImageWidget(assetImage: "assets/images/idea.png");
  static const Widget saving = ImageWidget(assetImage: "assets/images/sporenie.png");
}

class ImageWidget extends StatelessWidget {
  const ImageWidget({Key? key, this.assetImage = null, this.iconData = null, this.width, this.height}) : super(key: key);
  final String? assetImage;
  final IconData? iconData;
  final double? width;
  final double? height;

  double get effectiveWidth => width ?? 150;
  double get effectiveHeight => height ?? 150;

  @override
  Widget build(BuildContext context) {
    if (this.assetImage != null) {
      return Image.asset(
        this.assetImage!, 
        width: effectiveWidth,                
        height: effectiveHeight,              
      );
    }
    else if(this.iconData != null) {
      return Icon(this.iconData);
    }
    else {
      return Icon(IconData(0xf0555, fontFamily: 'MaterialIcons'));
    }

  }
}