const Map<String, String> lessonCategoryTitlesEn = {
  'peniaze_ako_koncept': 'Money',
  'potreby_vs_tuzby': 'Needs vs Wants',
  'prve_hospodarenie': 'First Experiences with Money',
  'sporenie': 'Saving',
  'cena_a_hodnota': 'Price and Value',
  'nakupovanie_a_rozhodovanie': 'Shopping and Decision-Making',
  'peniaze_v_rodine': 'Money in the Family',
  'praca_a_prijem': 'Work and Income',
  'rozpocet': 'Budget',
  'banky_a_ucty': 'Banks and Accounts',
  'digitalne_peniaze': 'Digital Money and Online Safety',
  'dlh_a_poziciavanie': 'Debt and Borrowing',
  'financne_chyby': 'Financial Mistakes',
  'prva_vyplata': 'First Paycheck',
  'stat_a_peniaze': 'Government and Money',
  'financna_rezerva': 'Emergency Fund',
  'inflacia': 'Inflation',
  'investovanie': 'Investing',
  'podnikanie': 'Entrepreneurship',
  'financna_samostatnost': 'Financial Independence',
};

const Map<String, String> lessonTitlesEn = {
  'co_su_peniaze': 'What is money',
  'preco_peniaze_existuju': 'Why money exists',
  'ako_ludia_platili_kedysi': 'How people paid in the past',
  'mince_bankovky_digitalne': 'Coins, banknotes, and digital money',
  'hodnota_peniazi': 'The value of money',
  'peniaze_nie_su_nekonecne': 'Money is not infinite',
  'odkial_peniaze_prichadzaju': 'Where money comes from',
  'co_potrebujem_na_zivot': 'What I need to live',
  'co_len_chcem': 'Just something I want',
  'preco_chceme_vec': 'Why we want things we do not need',
  'reklama_vplyv': 'Advertising and its influence',
  'emocionalne_nakupovanie': 'Emotional shopping',
  'vreckove': 'Pocket money',
  'ako_si_rozdelit_peniaze': 'How to divide money',
  'minut_teraz_vs_neskor': 'Spend now vs later',
  'preco_sa_oplati_planovat': 'Why planning is worth it',
  'male_financne_chyby': 'Small financial mistakes',
  'co_je_sporenie': 'What is saving?',
  'preco_si_odkladat': 'Why save money',
  'kratkodoby_vs_dlhodoby': 'Short-term goal vs long-term goal',
  'ako_si_vytvorit_rezervu': 'How to build a reserve',
  'pravidelne_male_sumy': 'Regular small amounts',
  'cena_vs_kvalita': 'Price vs quality',
  'lacne_vs_drahe': 'Cheap vs expensive',
  'vyhodna_kupa': 'What makes a good deal',
  'porovnavanie_cien': 'Comparing prices',
  'jednotkova_cena': 'Unit price',
  'ako_funguje_obchod': 'How a store works',
  'zlavy': 'Discounts',
  'akcie_a_marketingove_triky': 'Sales and marketing tricks',
  'impulzivne_nakupy': 'Impulse purchases',
  'ako_nenaletiet_na_reklamu': 'How not to fall for ads',
  'odkial_rodina_berie_peniaze': 'Where families get money',
  'vydavky_domacnosti': 'Household expenses',
  'byvanie_stoji_peniaze': 'Housing costs money',
  'jedlo_stoji_peniaze': 'Food costs money',
  'energie_stoja_peniaze': 'Energy costs money',
  'preco_ludia_pracuju': 'Why people work',
  'typy_povolani': 'Types of jobs',
  'plat_a_odmena': 'Salary and reward',
  'cas_je_hodnota': 'Time equals value',
  'produktivita': 'Productivity',
  'co_je_rozpocet': 'What is a budget?',
  'prijmy_a_vydavky': 'Income and expenses',
  'mesacne_planovanie': 'Monthly planning',
  'fixne_vydavky': 'Fixed expenses',
  'variabilne_vydavky': 'Variable expenses',
  'co_robi_banka': 'What a bank does',
  'bankovy_ucet': 'Bank account',
  'platobna_karta': 'Payment card',
  'pin': 'PIN',
  'prevod_penazi': 'Money transfer',
  'online_platby': 'Online payments',
  'hesla': 'Passwords',
  'scam': 'Scams',
  'falosne_e_shopy': 'Fake online shops',
  'podvody_na_internete': 'Online fraud',
  'influenceri_a_peniaze': 'Influencers and money',
  'co_je_dlh': 'What is debt?',
  'dobry_vs_zly_dlh': 'Good debt vs bad debt',
  'kedy_si_ludia_poziciavaju': 'When people borrow money',
  'urok': 'Interest',
  'preco_sa_dlh_zvacuje': 'Why debt grows',
  'rizika_poziciek': 'Risks of loans',
  'minanie_bez_planu': 'Spending without a plan',
  'nakupovanie_pod_emociami': 'Emotional spending',
  'zadlzenie': 'Debt',
  'fomo_pri_peniazoch': 'FOMO and money',
  'peer_pressure': 'Peer pressure',
  'hruba_vs_cista_mzda': 'Gross pay vs net pay',
  'odvody_jednoducho': 'Payroll deductions made simple',
  'brigada': 'Part-time job',
  'prvy_plat': 'First paycheck',
  'kam_miznu_peniaze': 'Where the money goes',
  'dane': 'Taxes',
  'na_co_idu_dane': 'What taxes pay for',
  'verejne_sluzby': 'Public services',
  'preco_stat_vybera_peniaze': 'Why the government collects money',
  'nudzove_peniaze': 'Emergency money',
  'necakane_vydavky': 'Unexpected expenses',
  'preco_mat_rezervu': 'Why have a reserve',
  'preco_vec_zdrazuju': 'Why things get more expensive',
  'peniaze_stracaju_hodnotu': 'Money loses value',
  'ako_inflacia_ovplyvnuje_zivot': 'How inflation affects daily life',
  'peniaze_mozu_pracovat': 'Money can work for you',
  'riziko_a_vynos': 'Risk and return',
  'dlhodobost': 'Long-term investing and compound interest',
  'zaklad_investovania': 'Investing basics',
  'diverzifikacia': 'Diversification',
  'ako_vznika_firma': 'How a company is created',
  'naklady_a_zisk': 'Costs and profit',
  'riziko_podnikania': 'Risks of entrepreneurship',
  'cena_produktu': 'Product pricing',
  'samostatne_byvanie': 'Living on your own',
  'mesacne_naklady_dospeleho': 'An adult\'s monthly expenses',
  'ako_prezit_mesiac': 'How to get through the month',
  'dlhodobe_planovanie': 'Long-term planning',
};
