import '../../models/item.dart';

/// Carpet items - floor coverings and rugs.
final List<Item> carpetItems = [
  Item(
    id: 'koberec_skibidi',
    name: 's',
    nameEn: 'Skibidi Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_skibidi.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_real',
    name: 'Realistický koberec',
    nameEn: 'Realistic Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_real.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_oblacik',
    name: 'Koberec s obláčikom',
    nameEn: 'Cloud Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_oblacik.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_modry',
    name: 'Modrý koberec',
    nameEn: 'Blue Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_modry.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_magia',
    name: 'Magický koberec',
    nameEn: 'Magic Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_magia.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_macka',
    name: 'Mačací koberec',
    nameEn: 'Cat Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_macka.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_macka_siva',
    name: 'Sivý mačací koberec',
    nameEn: 'Grey Cat Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_macka_siva.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_hnedy_ciary',
    name: 'Hnedý koberec s čiarami',
    nameEn: 'Brown Striped Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_hnedy_ciary.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_duha',
    name: 'Duhový koberec',
    nameEn: 'Rainbow Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_duha.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_cute',
    name: 'Zlatý koberec',
    nameEn: 'Golden Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_cute.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_babka',
    name: 'Babkin koberec',
    nameEn: 'Granny\'s Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_babka.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_4_znaky',
    name: 'Koberec so 4 znakmi',
    nameEn: '4 Symbols Rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_4_znaky.png',
    cost: 0,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
];