import '../../models/item.dart';

/// Carpet items - floor coverings and rugs.
final List<Item> carpetItems = [
  Item(
    id: 'koberec_skibidi',
    name: 'šialený koberec',
    nameEn: 'crazy rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_skibidi.png',
    cost: 60,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_real',
    name: 'magický koberec',
    nameEn: 'magic rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_real.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_oblacik',
    name: 'fialový koberec',
    nameEn: 'purple rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_oblacik.png',
    cost:70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_modry',
    name: 'modrý koberec',
    nameEn: 'blue rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_modry.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_magia',
    name: 'magický koberec 2',
    nameEn: 'magic rug 2',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_magia.png',
    cost: 80,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_macka',
    name: 'mačací koberec',
    nameEn: 'cat rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_macka.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_macka_siva',
    name: 'sivý mačací koberec',
    nameEn: 'grey cat rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_macka_siva.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_hnedy_ciary',
    name: 'dizajnový koberec',
    nameEn: 'designer rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_hnedy_ciary.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_duha',
    name: 'dúhový koberec',
    nameEn: 'rainbow rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_duha.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_cute',
    name: 'roztomilý koberec',
    nameEn: 'cute rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_cute.png',
    cost: 60,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_babka',
    name: 'starožitný koberec',
    nameEn: 'antique rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_babka.png',
    cost: 70,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
  Item(
    id: 'koberec_4_znaky',
    name: 'detský koberec',
    nameEn: 'kids rug',
    type: ItemType.decoration,
    texture: 'assets/images/items/koberec_4_znaky.png',
    cost: 60,
    hitboxId: 'koberec',
    scale: 0.11,
  ),
];