import '../../models/item.dart';

/// Decoration items - paintings, shelves, cabinets, plants, etc.
final List<Item> decorationItems = [
  // Windows/Mirrors
  Item(
    id: 'okno_normalne',
    name: 'Normálne okno',
    nameEn: 'Normal Window',
    type: ItemType.decoration,
    texture: 'assets/images/items/okno_normalne.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_modre',
    name: 'Modré okno',
    nameEn: 'Blue Window',
    type: ItemType.decoration,
    texture: 'assets/images/items/okno_modre.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_duhove',
    name: 'Duhové okno',
    nameEn: 'Rainbow Window',
    type: ItemType.decoration,
    texture: 'assets/images/items/okno_duhove.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_cierne',
    name: 'Čierne okno',
    nameEn: 'Black Window',
    type: ItemType.decoration,
    texture: 'assets/images/items/okno_cierne.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_zrkadlo',
    name: 'Zrkadlo',
    nameEn: 'Mirror',
    type: ItemType.decoration,
    texture: 'assets/images/items/okno_zrkadlo.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),

  // Paintings
  Item(
    id: 'obraz_tvary',
    name: 'Obraz s tvarmi',
    nameEn: 'Shapes Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_tvary.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_stastne_zvieratka',
    name: 'Obraz so šťastnými zvieratkami',
    nameEn: 'Happy Animals Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_stastne_zvieratka.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_skibidi',
    name: 'Skibidi obraz',
    nameEn: 'Skibidi Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_skibidi.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_salvador_dali',
    name: 'Obraz Salvadora Daliho',
    nameEn: 'Salvador Dalí Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_salvador_dali.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_nastenka',
    name: 'Nástenka',
    nameEn: 'Notice Board',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_nastenka.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_drak',
    name: 'Obraz draka',
    nameEn: 'Dragon Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_drak.png',
    cost: 0,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_aliens',
    name: 'Obraz s mimozemšťanom',
    nameEn: 'Alien Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_aliens.png',
    cost: 0,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'obraz_poník',
    name: 'Obraz s poníkom',
    nameEn: 'Pony Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_poník.png',
    cost: 0,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'obraz_s_chrumkom',
    name: 'Chrumko v obraze',
    nameEn: 'Chrumko Painting',
    type: ItemType.decoration,
    texture: 'assets/images/items/obraz_s_chrumkom.png',
    cost: 75,
    hitboxId: null,
    scale: 0.11,
  ),

  // Flowers/Plants
  Item(
    id: 'kvietok_s_chrumkom',
    name: 'Chrumko na kvietku',
    nameEn: 'Chrumko Flower',
    type: ItemType.decoration,
    texture: 'assets/images/items/kvietok_s_chrumkom.png',
    cost: 55,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'kvietok_alien',
    name: 'Mimozemsky kvietok',
    nameEn: 'Alien Flower',
    type: ItemType.decoration,
    texture: 'assets/images/items/kvietok_alien.png',
    cost: 50,
    hitboxId: null,
    scale: 0.12,
  ),
  Item(
    id: 'kvietok_y',
    name: 'Kvietky',
    nameEn: 'Flowers',
    type: ItemType.decoration,
    texture: 'assets/images/items/kvietok_y.png',
    cost: 50,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'kvietok_ruzovy',
    name: 'Ruzovy kvietok',
    nameEn: 'Pink Flower',
    type: ItemType.decoration,
    texture: 'assets/images/items/kvietok_ruzovy.png',
    cost: 50,
    hitboxId: null,
    scale: 0.15,
  ),
];