import '../../models/item.dart';

/// Decoration items - paintings, shelves, cabinets, plants, etc.
final List<Item> decorationItems = [
  // Animals
  Item(
    id: 'hoblub',
    name: 'holub',
    nameEn: 'pigeon',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/hoblub.png',
    cost: 100,
    hitboxId: null,
    scale: 0.03,
  ),
  Item(
    id: 'macka_cierna',
    name: 'čierna mačka',
    nameEn: 'black cat',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/macka_cierna.png',
    cost: 120,
    hitboxId: null,
    scale: 0.045,
  ),
  Item(
    id: 'macka_oranzova',
    name: 'ryšavá mačka',
    nameEn: 'ginger cat',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/macka_oranzova.png',
    cost: 120,
    hitboxId: null,
    scale: 0.06,
  ),
  Item(
    id: 'macka_ruzova',
    name: 'ružová mačka',
    nameEn: 'pink cat',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/macka_ruzova.png',
    cost: 120,
    hitboxId: null,
    scale: 0.04,
  ),
  Item(
    id: 'morca',
    name: 'morské prasiatko',
    nameEn: 'guinea pig',
    type: ItemType.decoration,    subtype: ItemSubtype.pets,    texture: 'assets/images/items/morca.png',
    cost: 100,
    hitboxId: null,
    scale: 0.03,
  ),
  Item(
    id: 'psik_jazvecik',
    name: 'jazvečík',
    nameEn: 'dachshund',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/psik_jazvecik.png',
    cost: 120,
    hitboxId: null,
    scale: 0.07,
  ),
  Item(
    id: 'psik_maly',
    name: 'čivava',
    nameEn: 'chihuahua',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/psik_maly.png',
    cost: 120,
    hitboxId: null,
    scale: 0.055,
  ),
  Item(
    id: 'psik_velky',
    name: 'Border kólia',
    nameEn: 'Border Collie',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/psik_velky.png',
    cost: 130,
    hitboxId: null,
    scale: 0.05,
  ),
  Item(
    id: 'zajacik',
    name: 'zajačik',
    nameEn: 'bunny',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/zajacik.png',
    cost: 100,
    hitboxId: null,
    scale: 0.04,
  ),
  Item(
    id: 'chrumko',
    name: 'Chrumko',
    nameEn: 'Chrumko',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/chrumko.png',
    cost: 300,
    hitboxId: null,
    scale: 0.05,
  ),
  Item(
    id: 'chrumko_macka',
    name: 'Chrumko ako mačka',
    nameEn: 'Chrumko as cat',
    type: ItemType.decoration,
    subtype: ItemSubtype.pets,
    texture: 'assets/images/items/chrumko_macka.png',
    cost: 200,
    hitboxId: null,
    scale: 0.05,
  ),

  // Windows/Mirrors
  Item(
    id: 'okno_normalne',
    name: 'klasické okno',
    nameEn: 'basic window',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/okno_normalne.png',
    cost: 80,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_modre',
    name: 'modré okno',
    nameEn: 'blue window',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/okno_modre.png',
    cost: 80,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_duhove',
    name: 'dúhové okno',
    nameEn: 'rainbow window',
    type: ItemType.decoration,    subtype: ItemSubtype.wallDecor,    texture: 'assets/images/items/okno_duhove.png',
    cost: 100,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_cierne',
    name: 'čierne okno',
    nameEn: 'black window',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/okno_cierne.png',
    cost: 80,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'okno_zrkadlo',
    name: 'zrkadlo',
    nameEn: 'mirror',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/okno_zrkadlo.png',
    cost: 50,
    hitboxId: 'obraz',
    scale: 0.11,
  ),

  // Paintings
  Item(
    id: 'obraz_tvary',
    name: 'moderný obraz',
    nameEn: 'modern painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_tvary.png',
    cost: 60,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_stastne_zvieratka',
    name: 'obraz s poníkmi',
    nameEn: 'painting with ponies',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_stastne_zvieratka.png',
    cost: 70,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_skibidi',
    name: 'šialený obraz',
    nameEn: 'crazy painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_skibidi.png',
    cost: 70,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_salvador_dali',
    name: 'obraz Salvador Dali',
    nameEn: 'Salvador Dalí painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_salvador_dali.png',
    cost: 90,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_nastenka',
    name: 'nástenka',
    nameEn: 'notice board',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_nastenka.png',
    cost: 50,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_drak',
    name: 'obraz draka',
    nameEn: 'dragon painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_drak.png',
    cost: 70,
    hitboxId: 'obraz',
    scale: 0.11,
  ),
  Item(
    id: 'obraz_aliens',
    name: 'obraz s mimozemšťanom',
    nameEn: 'alien painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_aliens.png',
    cost: 70,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'obraz_poník',
    name: 'obraz s poníkom',
    nameEn: 'pony painting',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_poník.png',
    cost: 70,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'obraz_s_chrumkom',
    name: 'obraz s Chrumkom',
    nameEn: 'painting with Chrumko',
    type: ItemType.decoration,
    subtype: ItemSubtype.wallDecor,
    texture: 'assets/images/items/obraz_s_chrumkom.png',
    cost: 80,
    hitboxId: null,
    scale: 0.11,
  ),

  // Flowers/Plants
  Item(
    id: 'kvietok_s_chrumkom',
    name: 'kvietok s Chrumkom',
    nameEn: 'flower with Chrumko',
    type: ItemType.decoration,
    subtype: ItemSubtype.plants,
    texture: 'assets/images/items/kvietok_s_chrumkom.png',
    cost: 50,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'kvietok_alien',
    name: 'mimozemský kvietok',
    nameEn: 'alien flower',
    type: ItemType.decoration,    subtype: ItemSubtype.plants,    texture: 'assets/images/items/kvietok_alien.png',
    cost: 50,
    hitboxId: null,
    scale: 0.12,
  ),
  Item(
    id: 'kvietok_y',
    name: 'kvietky',
    nameEn: 'flowers',
    type: ItemType.decoration,
    subtype: ItemSubtype.plants,
    texture: 'assets/images/items/kvietok_y.png',
    cost: 50,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'kvietok_ruzovy',
    name: 'ružový kvietok',
    nameEn: 'pink flower',
    type: ItemType.decoration,
    subtype: ItemSubtype.plants,
    texture: 'assets/images/items/kvietok_ruzovy.png',
    cost: 50,
    hitboxId: null,
    scale: 0.15,
  ),
];