import '../../models/item.dart';

/// Door items
final List<Item> doorItems = [
  Item(
    id: 'dvere_biele',
    name: 'biele Dvere',
    nameEn: 'white Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_biele.png',
    cost: 70,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_hnede',
    name: 'hnedé Dvere',
    nameEn: 'brown Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_hnede.png',
    cost: 70,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_cierne',
    name: 'čierne Dvere',
    nameEn: 'black Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_cierne.png',
    cost: 80,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_portal',
    name: 'dvere do iného sveta',
    nameEn: 'door to another world',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_portal.png',
    cost: 80,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_ruzove',
    name: 'ružové Dvere',
    nameEn: 'pink Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_ruzove.png',
    cost: 100,
    hitboxId: 'dvere_obluk',
    scale: 0.11,
  ),
];