import '../../models/item.dart';

/// Door items
final List<Item> doorItems = [
  Item(
    id: 'dvere_biele',
    name: 'Biele Dvere',
    nameEn: 'White Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_biele.png',
    cost: 0,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_hnede',
    name: 'Hnede Dvere',
    nameEn: 'Brown Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_hnede.png',
    cost: 0,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_cierne',
    name: 'Čierne Dvere',
    nameEn: 'Black Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_cierne.png',
    cost: 0,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_portal',
    name: 'Portal Dvere',
    nameEn: 'Portal Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_portal.png',
    cost: 0,
    hitboxId: 'dvere',
    scale: 0.11,
  ),
  Item(
    id: 'dvere_ruzove',
    name: 'Ružové Dvere',
    nameEn: 'Pink Door',
    type: ItemType.door,
    texture: 'assets/images/items/dvere_ruzove.png',
    cost: 0,
    hitboxId: 'dvere_obluk',
    scale: 0.11,
  ),
];