import '../../models/item.dart';

/// Furniture items - sofas, beds, cabinets, wardrobes
final List<Item> furnitureItems = [
  Item(
    id: 'gauc_zniceny2',
    name: 'Zničený gauč 2',
    nameEn: 'Ruined Sofa 2',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_zniceny2.png',
    cost: 0,
    hitboxId: null, //OPRAVIŤ
    scale: 0.14,
  ),

  Item(
    id: 'gauc_zniceny1',
    name: 'Zničený gauč 1',
    nameEn: 'Ruined Sofa 1',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_zniceny1.png',
    cost: 0,
    hitboxId: null, //OPRAVIŤ
    scale: 0.14,
  ),

  Item(
    id: 'postel_znicena',
    name: 'Zničená posteľ',
    nameEn: 'Ruined Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_znicena.png',
    cost: 0,
    hitboxId: null,
    scale: 0.13,
  ),

  Item(
    id: 'polica_kniznica_cierna',
    name: 'Čierna knižnica',
    nameEn: 'Black Bookcase',
    type: ItemType.decoration,
    texture: 'assets/images/items/polica_kniznica_cierna.png',
    cost: 0,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'polica',
    name: 'Basic polica',
    nameEn: 'Basic Shelf',
    type: ItemType.decoration,
    texture: 'assets/images/items/polica.png',
    cost: 0,
    hitboxId: null,
    scale: 0.125,
  ),
  Item(
    id: 'polica_dizajnová',
    name: 'Dizajnová polica',
    nameEn: 'Designer Shelf',
    type: ItemType.decoration,
    texture: 'assets/images/items/polica_dizajnová.png',
    cost: 0,
    hitboxId: null,
    scale: 0.13,
  ),
  Item(
    id: 'skriňa_rohová',
    name: 'Rohová skriňa',
    nameEn: 'Corner Cabinet',
    type: ItemType.decoration,
    texture: 'assets/images/items/skriňa_rohová.png',
    cost: 0,
    hitboxId: null,
    scale: 0.17,
  ),
  Item(
    id: 'skriňa_poličky',
    name: 'Skriňa s poličkami',
    nameEn: 'Shelved Cabinet',
    type: ItemType.decoration,
    texture: 'assets/images/items/skriňa_poličky.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'skriňa_nízka',
    name: 'Nízká skriňa',
    nameEn: 'Low Cabinet',
    type: ItemType.decoration,
    texture: 'assets/images/items/skriňa_nízka.png',
    cost: 0,
    hitboxId: null,
    scale: 0.125,
  ),
  Item(
    id: 'posteľ_zámok',
    name: 'Posteľ na zámku',
    nameEn: 'Castle Bed',
    type: ItemType.decoration,
    texture: 'assets/images/items/posteľ_zámok.png',
    cost: 0,
    hitboxId: null,
    scale: 0.16,
  ),
  Item(
    id: 'gauc_zeleny',
    name: 'Zelený gauč',
    nameEn: 'Green Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_zeleny.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_ruzovy',
    name: 'Ružový gauč',
    nameEn: 'Pink Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_ruzovy.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_ruzovy_oblacik',
    name: 'Gauč ružový obláčik',
    nameEn: 'Pink Cloud Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_ruzovy_oblacik.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_modry',
    name: 'Modrý gauč',
    nameEn: 'Blue Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_modry.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_modry_oblacik',
    name: 'Gauč modrý obláčik',
    nameEn: 'Blue Cloud Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_modry_oblacik.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_dreveny',
    name: 'Drevený gáuč',
    nameEn: 'Wooden Sofa',
    type: ItemType.furniture,
    texture: 'assets/images/items/gauc_dreveny.png',
    cost: 0,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'posteľ_základná',
    name: 'Základná posteľ',
    nameEn: 'Basic Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/posteľ_základná.png',
    cost: 0,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'posteľ_dievčenská',
    name: 'Dievčenská posteľ',
    nameEn: 'Girls\' Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/posteľ_dievčenská.png',
    cost: 300,
    hitboxId: null,
    scale: 0.16,
  ),
  Item(
    id: 'skriňa_šatník',
    name: 'Šatník',
    nameEn: 'Wardrobe',
    type: ItemType.furniture,
    texture: 'assets/images/items/skriňa_šatník.png',
    cost: 175,
    hitboxId: null,
    scale: 0.2,
  ),

  Item(
    id: 'police_mile',
    name: 'Milé poličky',
    nameEn: 'Cute Shelf',
    type: ItemType.furniture,
    texture: 'assets/images/items/police_mile.png',
    cost: 0,
    hitboxId: null,
    scale: 0.09,
  ),

  Item(
    id: 'skrina_rohove_boxy',
    name: 'Rohová skriňa - boxy',
    nameEn: 'Corner Cabinet - Boxes',
    type: ItemType.furniture,
    texture: 'assets/images/items/skrina_rohove_boxy.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),

  Item(
    id: 'skrina_rohove_policky',
    name: 'Rohové poličky',
    nameEn: 'Corner Cabinet - Shelves',
    type: ItemType.furniture,
    texture: 'assets/images/items/skrina_rohove_policky.png',
    cost: 0,
    hitboxId: null,
    scale: 0.12,
  ),

  Item(
    id: 'skrina_rohove_policky_macko',
    name: 'Rohová skriňa - poličky s mackom',
    nameEn: 'Corner Cabinet - Shelves with Cat',
    type: ItemType.furniture,
    texture: 'assets/images/items/skrina_rohove_policky_macko.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),

  Item(
    id: 'postel_chlapcenska1',
    name: 'Chlapčenská posteľ 1',
    nameEn: 'Boys Bed 1',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_chlapcenska1.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_chlapcenska2',
    name: 'Chlapčenská posteľ 2',
    nameEn: 'Boys Bed 2',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_chlapcenska2.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_dieta',
    name: 'Detská posteľ',
    nameEn: 'Child Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_dieta.png',
    cost: 0,
    hitboxId: 'postel_obluky',
    scale: 0.16,
  ),

  Item(
    id: 'postel_jemna',
    name: 'Jemná posteľ',
    nameEn: 'Gentle Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_jemna.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_ponik1',
    name: 'Poníková posteľ 1',
    nameEn: 'Pony Bed 1',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_ponik1.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_ponik2',
    name: 'Poníková posteľ 2',
    nameEn: 'Pony Bed 2',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_ponik2.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_ponik3',
    name: 'Poníková posteľ 3',
    nameEn: 'Pony Bed 3',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_ponik3.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_ponik4',
    name: 'Poníková posteľ 4',
    nameEn: 'Pony Bed 4',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_ponik4.png',
    cost: 0,
    hitboxId: 'postel_obluky',
    scale: 0.16,
  ),

  Item(
    id: 'postel_portal',
    name: 'Portálová posteľ',
    nameEn: 'Portal Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_portal.png',
    cost: 0,
    hitboxId: null,
    scale: 0.16,
  ),

  Item(
    id: 'postel_velka_modra',
    name: 'Veľká modrá posteľ',
    nameEn: 'Big Blue Bed',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_velka_modra.png',
    cost: 0,
    hitboxId: 'postel_velka_opierka',
    scale: 0.16,
  ),

  Item(
    id: 'postel_zamok_tmava',
    name: 'Zamok - tmavá',
    nameEn: 'Castle - Dark',
    type: ItemType.furniture,
    texture: 'assets/images/items/postel_zamok_tmava.png',
    cost: 0,
    hitboxId: 'posteľ_zámok',
    scale: 0.16,
  ),
];