import '../../models/item.dart';

/// Furniture items - sofas, beds, cabinets, wardrobes
final List<Item> furnitureItems = [
  Item(
    id: 'gauc_zniceny2',
    name: 'zničená pohovka 2',
    nameEn: 'ruined sofa 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_zniceny2.png',
    cost: 5,
    hitboxId: null, //OPRAVIŤ
    scale: 0.14,
  ),
  Item(
    id: 'gauc_zniceny1',
    name: 'zničená pohovka 1',
    nameEn: 'ruined sofa 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_zniceny1.png',
    cost: 5,
    hitboxId: null, //OPRAVIŤ
    scale: 0.14,
  ),
  Item(
    id: 'postel_znicena',
    name: 'zničená posteľ',
    nameEn: 'ruined bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_znicena.png',
    cost: 5,
    hitboxId: null,
    scale: 0.13,
  ),
  Item(
    id: 'polica_kniznica_cierna',
    name: 'čierny regál',
    nameEn: 'black shelf',
    type: ItemType.decoration,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/polica_kniznica_cierna.png',
    cost: 200,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'polica',
    name: 'klasická polica',
    nameEn: 'basic shelf',
    type: ItemType.decoration,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/polica.png',
    cost: 50,
    hitboxId: null,
    scale: 0.125,
  ),
  Item(
    id: 'polica_dizajnová',
    name: 'dizajnová polica',
    nameEn: 'designer shelf',
    type: ItemType.decoration,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/polica_dizajnová.png',
    cost: 70,
    hitboxId: null,
    scale: 0.13,
  ),
  Item(
    id: 'skriňa_rohová',
    name: 'rohová polica 1',
    nameEn: 'corner shelf 1',
    type: ItemType.decoration,    subtype: ItemSubtype.storage,    texture: 'assets/images/items/skriňa_rohová.png',
    cost: 80,
    hitboxId: null,
    scale: 0.17,
  ),
  Item(
    id: 'skriňa_poličky',
    name: 'regál s poličkami',
    nameEn: 'shelved cabinet',
    type: ItemType.decoration,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/skriňa_poličky.png',
    cost: 100,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'skriňa_nízka',
    name: 'otvorená nízka skriňa',
    nameEn: 'open low cabinet',
    type: ItemType.decoration,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/skriňa_nízka.png',
    cost: 120,
    hitboxId: null,
    scale: 0.125,
  ),
  Item(
    id: 'posteľ_zámok',
    name: 'rozprávková posteľ 1',
    nameEn: 'fairytale bed',
    type: ItemType.decoration,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/posteľ_zámok.png',
    cost: 250,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'gauc_zeleny',
    name: 'zelená pohovka',
    nameEn: 'green sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_zeleny.png',
    cost: 150,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_ruzovy',
    name: 'ružová pohovka',
    nameEn: 'pink sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_ruzovy.png',
    cost: 150,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_ruzovy_oblacik',
    name: 'roztomilá ružová pohovka',
    nameEn: 'cute pink sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_ruzovy_oblacik.png',
    cost: 200,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_modry',
    name: 'modrá pohovka',
    nameEn: 'blue sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_modry.png',
    cost: 150,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_modry_oblacik',
    name: 'roztomilá modrá pohovka',
    nameEn: 'cute blue sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_modry_oblacik.png',
    cost: 200,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'gauc_dreveny',
    name: 'starožitná pohovka',
    nameEn: 'antique sofa',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/gauc_dreveny.png',
    cost: 150,
    hitboxId: 'gauc',
    scale: 0.185,
  ),
  Item(
    id: 'posteľ_základná',
    name: 'klasická posteľ',
    nameEn: 'basic bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/posteľ_základná.png',
    cost: 120,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'posteľ_dievčenská',
    name: 'ružová posteľ',
    nameEn: 'pink bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/posteľ_dievčenská.png',
    cost: 200,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'skriňa_šatník',
    name: 'šatníková skriňa',
    nameEn: 'wardrobe',
    type: ItemType.furniture,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/skriňa_šatník.png',
    cost: 150,
    hitboxId: null,
    scale: 0.2,
  ),
  Item(
    id: 'police_mile',
    name: 'roztomilá polička',
    nameEn: 'cute shelf',
    type: ItemType.furniture,
    subtype: ItemSubtype.storage,
    texture: 'assets/images/items/police_mile.png',
    cost: 100,
    hitboxId: null,
    scale: 0.09,
  ),
  Item(
    id: 'skrina_rohove_boxy',
    name: 'rohová polica 2',
    nameEn: 'corner shelf 2',
    type: ItemType.furniture,    subtype: ItemSubtype.storage,    texture: 'assets/images/items/skrina_rohove_boxy.png',
    cost: 100,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'skrina_rohove_policky',
    name: 'rohová polica 3',
    nameEn: 'corner shelf 3',
    type: ItemType.furniture,    subtype: ItemSubtype.storage,    texture: 'assets/images/items/skrina_rohove_policky.png',
    cost: 100,
    hitboxId: null,
    scale: 0.12,
  ),
  Item(
    id: 'skrina_rohove_policky_macko',
    name: 'rohová polica 4',
    nameEn: 'corner shelf 4',
    type: ItemType.furniture,    subtype: ItemSubtype.storage,    texture: 'assets/images/items/skrina_rohove_policky_macko.png',
    cost: 100,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'postel_chlapcenska1',
    name: 'modrá posteľ 1',
    nameEn: 'blue bed 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_chlapcenska1.png',
    cost: 200,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_chlapcenska2',
    name: 'raketová posteľ',
    nameEn: 'rocket bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_chlapcenska2.png',
    cost: 200,
    hitboxId: 'postel_velka_opierka',
    scale: 0.13,
  ),
  Item(
    id: 'postel_dieta',
    name: 'detská posteľ',
    nameEn: 'child bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_dieta.png',
    cost: 200,
    hitboxId: 'postel_obluky',
    scale: 0.14,
  ),
  Item(
    id: 'postel_jemna',
    name: 'jednoduchá posteľ',
    nameEn: 'simple bed',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_jemna.png',
    cost: 180,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_ponik1',
    name: 'poníková posteľ 1',
    nameEn: 'pony bed 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_ponik1.png',
    cost: 200,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_ponik2',
    name: 'poníková posteľ 2',
    nameEn: 'pony bed 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_ponik2.png',
    cost: 200,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_ponik3',
    name: 'poníková posteľ 3',
    nameEn: 'pony bed 3',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_ponik3.png',
    cost: 200,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_ponik4',
    name: 'poníková posteľ 4',
    nameEn: 'pony bed 4',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_ponik4.png',
    cost: 200,
    hitboxId: 'postel_obluky',
    scale: 0.14,
  ),
  Item(
    id: 'postel_portal',
    name: 'posteľ z iného sveta',
    nameEn: 'bed from another world',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_portal.png',
    cost: 250,
    hitboxId: null,
    scale: 0.14,
  ),
  Item(
    id: 'postel_velka_modra',
    name: 'modrá posteľ 2',
    nameEn: 'blue bed 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_velka_modra.png',
    cost: 180,
    hitboxId: 'postel_velka_opierka',
    scale: 0.14,
  ),
  Item(
    id: 'postel_zamok_tmava',
    name: 'rozprávková posteľ 2',
    nameEn: 'fairytale bed 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.beds,
    texture: 'assets/images/items/postel_zamok_tmava.png',
    cost: 250,
    hitboxId: 'posteľ_zámok',
    scale: 0.14,
  ),
  // Chairs
  Item(
    id: 'stolicka_klasicka',
    name: 'klasická stolička',
    nameEn: 'classic chair',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_klasicka.png',
    cost: 50,
    hitboxId: null,
    scale: 0.09,
  ),
  Item(
    id: 'stolicka_ruzova_klasicka_1',
    name: 'ružová stolička 1',
    nameEn: 'pink chair 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_ruzova_klasicka_1.png',
    cost: 50,
    hitboxId: null,
    scale: 0.082,
  ),
  Item(
    id: 'stolicka_ruzova_klasicka_2',
    name: 'ružová stolička 2',
    nameEn: 'pink chair 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_ruzova_klasicka_2.png',
    cost: 50,
    hitboxId: null,
    scale: 0.085,
  ),
  Item(
    id: 'stolicka_dievcenska_1',
    name: 'dievčenská stolička 1',
    nameEn: 'girl chair 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_dievcenska_1.png',
    cost: 100,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'stolicka_dievcenska_2',
    name: 'dievčenská stolička 2',
    nameEn: 'girl chair 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_dievcenska_2.png',
    cost: 100,
    hitboxId: null,
    scale: 0.07,
  ),
  Item(
    id: 'stolicka_cyberpunk_1',
    name: 'cyberpunková stolička 1',
    nameEn: 'cyberpunk chair 1',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_cyberpunk_1.png',
    cost: 100,
    hitboxId: null,
    scale: 0.17,
  ),
  Item(
    id: 'stolicka_cyberpunk_2',
    name: 'cyberpunková stolička 2',
    nameEn: 'cyberpunk chair 2',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_cyberpunk_2.png',
    cost: 100,
    hitboxId: null,
    scale: 0.07,
  ),
  Item(
    id: 'stolicka_oblacik',
    name: 'oblačiková stolička',
    nameEn: 'cloud chair',
    type: ItemType.furniture,
    subtype: ItemSubtype.seating,
    texture: 'assets/images/items/stolicka_oblacik.png',
    cost: 50,
    hitboxId: null,
    scale: 0.07,
  ),
  // Lamps
  Item(
    id: 'lampa_chrumko',
    name: 'Chrumko lampa',
    nameEn: 'Chrumko lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_chrumko.png',
    cost: 70,
    hitboxId: null,
    scale: 0.07,
  ),
  Item(
    id: 'lampa_drak_modry',
    name: 'modrá dračia lampa',
    nameEn: 'blue dragon lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_drak_modry.png',
    cost: 60,
    hitboxId: 'lampa_drak',
    scale: 0.013,
  ),
  Item(
    id: 'lampa_drak_ruzova',
    name: 'ružová dračia lampa',
    nameEn: 'pink dragon lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_drak_ruzova.png',
    cost: 60,
    hitboxId: 'lampa_drak',
    scale: 0.013,
  ),
  Item(
    id: 'lampa_drak_zelena',
    name: 'zelená dračia lampa',
    nameEn: 'green dragon lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_drak_zelena.png',
    cost: 60,
    hitboxId: 'lampa_drak',
    scale: 0.013,
  ),
  Item(
    id: 'lampa_hviezda_fialova',
    name: 'fialová hviezda lampa',
    nameEn: 'purple star lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_hviezda_fialova.png',
    cost: 60,
    hitboxId: 'lampa_hviezda',
    scale: 0.015,
  ),
  Item(
    id: 'lampa_hviezda_modra',
    name: 'modrá hviezda lampa',
    nameEn: 'blue star lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_hviezda_modra.png',
    cost: 60,
    hitboxId: 'lampa_hviezda',
    scale: 0.015,
  ),
  Item(
    id: 'lampa_oblacik_modra',
    name: 'modrá oblačiková lampa',
    nameEn: 'blue cloud lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_oblacik_modra.png',
    cost: 60,
    hitboxId: 'lampa_oblacik',
    scale: 0.015,
  ),
  Item(
    id: 'lampa_oblacik_ruzova',
    name: 'ružová oblačiková lampa',
    nameEn: 'pink cloud lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_oblacik_ruzova.png',
    cost: 60,
    hitboxId: 'lampa_oblacik',
    scale: 0.015,
  ),
  Item(
    id: 'lampa_oblacik_zlta',
    name: 'žltá oblačiková lampa',
    nameEn: 'yellow cloud lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_oblacik_zlta.png',
    cost: 60,
    hitboxId: 'lampa_oblacik',
    scale: 0.015,
  ),
  Item(
    id: 'lampa_podlahova_fialova',
    name: 'fialová podlahová lampa',
    nameEn: 'purple floor lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_podlahova_fialova.png',
    cost: 100,
    hitboxId: 'lampa_podlahova',
    scale: 0.04,
  ),
  Item(
    id: 'lampa_podlahova_modra',
    name: 'modrá podlahová lampa',
    nameEn: 'blue floor lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_podlahova_modra.png',
    cost: 100,
    hitboxId: 'lampa_podlahova',
    scale: 0.04,
  ),
  Item(
    id: 'lampa_tvary_fialova',
    name: 'fialová lampa s tvarmi',
    nameEn: 'purple shapes lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_tvary_fialova.png',
    cost: 60,
    hitboxId: 'lampa_tvary',
    scale: 0.022,
  ),
  Item(
    id: 'lampa_tvary_modra',
    name: 'modrá lampa s tvarmi',
    nameEn: 'blue shapes lamp',
    type: ItemType.furniture,
    subtype: ItemSubtype.lighting,
    texture: 'assets/images/items/lampa_tvary_modra.png',
    cost: 60,
    hitboxId: 'lampa_tvary',
    scale: 0.022,
  ),
];
