import '../../models/item.dart';

/// Table items - various desk and table styles
final List<Item> tableItems = [
  Item(
    id: 'stol_basic',
    name: 'Klasický stôl',
    nameEn: 'Basic Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_basic.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_aura',
    name: 'Aura stôl',
    nameEn: 'Aura Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_aura.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_cyberpunk',
    name: 'Futuristický stôl',
    nameEn: 'Cyberpunk Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_cyberpunk.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_delta',
    name: 'Delta stôl',
    nameEn: 'Delta Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_delta.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_dievcensky',
    name: 'Dievčenský stôl',
    nameEn: 'Girls\' Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_dievcensky.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_drak',
    name: 'Stól draka',
    nameEn: 'Dragon Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_drak.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_lavica',
    name: 'Lavica',
    nameEn: 'Desk',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_lavica.png',
    cost: 0,
    hitboxId: null,
    scale: 0.15,
  ),
  Item(
    id: 'stol_modry',
    name: 'Modrý stôl',
    nameEn: 'Blue Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_modry.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_flaky',
    name: 'Fľakaty stôl',
    nameEn: 'Flaky Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_flaky.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_plaz',
    name: 'Stôl mora',
    nameEn: 'Sea Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_plaz.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_oblacik',
    name: 'Obláčikový stôl',
    nameEn: 'Cloud Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_oblacik.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_mramor',
    name: 'Mramorový stôl',
    nameEn: 'Marble Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_mramor.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_ruzovy_oblacik',
    name: 'Stôl ružového obláčiku',
    nameEn: 'Pink Cloud Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_ruzovy_oblacik.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_roald_dahl',
    name: 'Roald Dahl stôl',
    nameEn: 'Roald Dahl Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_roald_dahl.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
  Item(
    id: 'stol_smajlik',
    name: ':) stôl',
    nameEn: 'Smiley Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_smajlik.png',
    cost: 0,
    hitboxId: 'stol',
    scale: 0.15,
  ),
];
