import '../../models/item.dart';

/// Table items - various desk and table styles
final List<Item> tableItems = [
  Item(
    id: 'stol_basic',
    name: 'klasický stôl',
    nameEn: 'basic table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_basic.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_aura',
    name: 'aura stôl',
    nameEn: 'aura table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_aura.png',
    cost: 150,
    hitboxId: null,
    scale: 0.095,
  ),
  Item(
    id: 'stol_cyberpunk',
    name: 'futuristický stôl',
    nameEn: 'cyberpunk table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_cyberpunk.png',
    cost: 250,
    hitboxId: null,
    scale: 0.11,
  ),
  Item(
    id: 'stol_delta',
    name: 'herný stôl',
    nameEn: 'gaming table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_delta.png',
    cost: 150,
    hitboxId: null,
    scale: 0.08,
  ),
  Item(
    id: 'stol_dievcensky',
    name: 'roztomilý ružový stôl',
    nameEn: 'cutepink table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_dievcensky.png',
    cost: 250,
    hitboxId: null,
    scale: 0.105,
  ),
  Item(
    id: 'stol_drak',
    name: 'stôl drak',
    nameEn: 'dragon table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_drak.png',
    cost: 250,
    hitboxId: null,
    scale: 0.095,
  ),
  Item(
    id: 'stol_lavica',
    name: 'lavica',
    nameEn: 'desk',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_lavica.png',
    cost: 170,
    hitboxId: null,
    scale: 0.098,
  ),
  Item(
    id: 'stol_modry',
    name: 'modrý stôl',
    nameEn: 'blue table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_modry.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_flaky',
    name: 'umelecký stôl',
    nameEn: 'artistic table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_flaky.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_plaz',
    name: 'morský stôl',
    nameEn: 'sea table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_plaz.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_oblacik',
    name: 'obláčikový stôl',
    nameEn: 'cloud table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_oblacik.png',
    cost: 160,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_mramor',
    name: 'mramorový stôl',
    nameEn: 'marble table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_mramor.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_ruzovy_oblacik',
    name: 'ružový stôl',
    nameEn: 'pink table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_ruzovy_oblacik.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_salvador_dali',
    name: 'stôl Salvador Dali',
    nameEn: 'Salvador Dali Table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_salvador_dali.png',
    cost: 160,
    hitboxId: 'stol',
    scale: 0.095,
  ),
  Item(
    id: 'stol_smajlik',
    name: 'detský stôl',
    nameEn: 'kids table',
    type: ItemType.furniture,
    texture: 'assets/images/items/stol_smajlik.png',
    cost: 150,
    hitboxId: 'stol',
    scale: 0.095,
  ),
];
